export enum RequestStatus {
  VALIDATION_PENDING = 'VALIDATION_PENDING',
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
  HCM_VALIDATION_FAILED = 'HCM_VALIDATION_FAILED',
  HCM_SYNC_PENDING = 'HCM_SYNC_PENDING',
  HCM_SYNC_FAILED = 'HCM_SYNC_FAILED',
  APPROVED = 'APPROVED',
  CANCELLED = 'CANCELLED',
}

export enum OutboxJobStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  DEAD_LETTER = 'DEAD_LETTER',
}

export enum OutboxJobType {
  VALIDATE_LEAVE_REQUEST = 'VALIDATE_LEAVE_REQUEST',
  SYNC_APPROVED_LEAVE_TO_HCM = 'SYNC_APPROVED_LEAVE_TO_HCM',
}

export enum LeaveType {
  ANNUAL = 'ANNUAL',
  SICK = 'SICK',
}
